api:
    dashboard: true
entryPoints:
    http:
        address: :80
        http2:
            maxConcurrentStreams: 250
    https:
        address: :443
        http2:
            maxConcurrentStreams: 250
        http3: {}
global:
    sendAnonymousUsage: false
log:
    level: DEBUG
providers:
    swarm:
        endpoint: unix:///var/run/docker.sock
        exposedByDefault: false
        watch: true
        network: traefik_traefik_proxy
    file:
        filename: /etc/traefik/traefik-dynamic.yml
        watch: true
